/**
 * Any files not generated by svgr need to be exported here. svgr generates only icons that exist in the ipfs-css package.
 * By consuming this file, you can get all the icons available to ipfs-webui.
 */
export { default as GlyphPinCloud } from './hocs/GlyphPinCloud.js'
export * from './stroke-icons.js'
export * from './index.js'
