export default {
  '1c': ['1c'],
  'accesslog': ['log'],
  'actionscript': ['as', 'actionscript'],
  'apache': ['apache', 'apacheconf'],
  'applescript': ['applescript', 'osascript'],
  'arduino': ['ino'],
  'armasm': ['arm'],
  'asciidoc': ['adoc', 'asciidoc'],
  'aspectj': ['aspectj'],
  'autohotkey': ['autohotkey'],
  'autoit': ['autoit'],
  'avrasm': ['avrasm'],
  'axapta': ['axapta'],
  'bash': ['sh', 'zsh', 'bash'],
  'basic': ['basic'],
  'brainfuck': ['brainfuck', 'bf'],
  'cal': ['cal'],
  'capnproto': ['capnp'],
  'ceylon': ['ceylon'],
  'clojure': ['clj'],
  'cmake': ['cmake', 'cmake.in'],
  'coffeescript': ['coffee', 'litcoffee'],
  'cos': ['cos', 'cls'],
  'cpp': ['cpp', 'c++', 'c', 'h', 'h++', 'hpp'],
  'crmsh': ['crmsh', 'crm', 'pcmk'],
  'crystal': ['cr'],
  'cs': ['cs', 'csharp'],
  'csp': ['csp'],
  'css': ['css'],
  'd': ['d'],
  'dart': ['dart'],
  'delphi': ['delphi', 'dpr', 'dfm', 'pas', 'pascal', 'freepascal, lazarus', 'lpr', 'lfm'],
  'diff': ['diff', 'patch'],
  'django': ['django', 'jinja'],
  'dns': ['dns', 'zone', 'bind'],
  'dockerfile': ['dockerfile', 'docker'],
  'dos': ['dos', 'bat', 'cmd'],
  'dts': ['dts'],
  'dust': ['dst', 'dust'],
  'elixir': ['elixir', 'ex'],
  'elm': ['elm'],
  'erb': ['erb'],
  'erlang': ['erl'],
  'fix': ['fix'],
  'fortran': ['fortran', 'f90', 'f95'],
  'fsharp': ['fsharp', 'fs'],
  'gams': ['gams', 'gms'],
  'gauss': ['gauss', 'gss'],
  'gcode': ['gcode', 'nc'],
  'gherkin': ['gherkin', 'feature'],
  'glsl': ['glslv', 'vert', 'shader', 'frag'],
  'go': ['go'],
  'golo': ['golo'],
  'gradle': ['gradle'],
  'groovy': ['groovy'],
  'haml': ['haml'],
  'handlebars': ['hbs', 'handlebars', 'mustache'],
  'haskell': ['hs'],
  'haxe': ['hx'],
  'hsp': ['hsp'],
  'htmlbars': ['htmlbars'],
  'http': ['http', 'https'],
  'inform7': ['i7'],
  'ini': ['ini', 'conf'],
  'irpf90': ['irpf90'],
  'java': ['java', 'jsp'],
  'javascript': ['js', 'jsx'],
  'json': ['json'],
  'julia': ['jl'],
  'kotlin': ['kt', 'kts'],
  'lasso': ['lasso', 'lassoapp'],
  'less': ['less'],
  'lisp': ['el'],
  'livecodeserver': ['livecode'],
  'livescript': ['ls'],
  'lua': ['lua'],
  'makefile': ['make'],
  'markdown': ['md', 'markdown'],
  'mathematica': ['mma'],
  'matlab': ['matlab'],
  'maxima': ['maxima'],
  'mel': ['mel'],
  'mercury': ['mercury'],
  'mipsasm': ['mispasm'],
  'mizar': ['mizar'],
  'mojolicious': ['mojolicious'],
  'monkey': ['monkey'],
  'nginx': ['nginx', 'nginxconf'],
  'nimrod': ['nim'],
  'nix': ['nix'],
  'nsis': ['nsis'],
  'objectivec': ['mm', 'objc', 'obj-c'],
  'ocaml': ['ml'],
  'openscad': ['openscad', 'scad'],
  'oxygene': ['oxygene'],
  'parser3': ['parser3'],
  'perl': ['pl'],
  'pf': ['pf'],
  'php': ['php', 'php3', 'php4', 'php5', 'php6'],
  'powershell': ['ps'],
  'processing': ['processing'],
  'profile': ['profile'],
  'prolog': ['pro', 'p'],
  'protobuf': [],
  'puppet': [],
  'python': ['py'],
  'q': ['q'],
  'qml': ['qml'],
  'r': ['r'],
  'rib': [],
  'roboconf': [],
  'rsl': [],
  'ruby': ['rb'],
  'ruleslanguage': [],
  'rust': ['rs'],
  'scala': [],
  'scheme': [],
  'scilab': [],
  'scss': ['scss', 'sass'],
  'smali': [],
  'smalltalk': [],
  'sml': [],
  'sqf': [],
  'sql': [],
  'stan': [],
  'stata': [],
  'step21': [],
  'stylus': ['styl'],
  'swift': [],
  'taggerscript': [],
  'tcl': [],
  'tex': ['tex'],
  'thrift': ['thrift'],
  'tp': [],
  'twig': [],
  'typescript': ['ts'],
  'vala': [],
  'vbnet': [],
  'vbscript-html': [],
  'vbscript': [],
  'verilog': [],
  'vhdl': [],
  'vim': [],
  'x86asm': [],
  'xl': [],
  'xml': ['html', 'xml', 'htm'],
  'xquery': [],
  'yaml': ['yml', 'yaml'],
  'zephir': []
}
